### PR TITLE
[WIP] Make nodecolor a String instead of an Int

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by mkborregaard** [comment]
What's the purpose of this PR? It doesn't look ideal to hardcode the nodecolor

**Comment by asinghvi17** [comment]
Right, it's not - just figured out what that was.  I needed a branch to test changes off, so I used this...still, the behaviour where `color = 1 => color = palette[1]` is a little disconcerting.  Any particular reason for that?

**Comment by mkborregaard** [comment]
It's very useful in recipes to specify that the series should be taken from the active color palette and in which ordere

**Comment by asinghvi17** [comment]
so essentially specifying the series number?  I guess that makes sense.  Will close this PR, since I think I have this handled in MakieRecipes...

**Pull request closed without merging**
