### PR TITLE
Fix spectral method

### PR DESCRIPTION
**Pull request by JackDevine**
Without this PR, the added test would fail.

### CODE REVIEW

**Comment by JackDevine** [comment]
It seems that my test only works on Linux Julia 1.0 (the only version that I tested locally).

An alternative approach would be to use the spectral layout from NetworkLayouts.jl. That seems a little smarter than having two implementations of the same thing lying around.

**Comment by mkborregaard** [comment]
I agree that it's preferable to use the NetworkLayouts method.

**Comment by mkborregaard** [comment]
@JackDevine I see you are doing a lot of work on GraphRecipes currently - are you the one who got employed to create a good framework for graph plotting? If so we should probably discuss giving you push rights on the repo, if you want.

**Comment by JackDevine** [comment]
@mkborregaard Yes, I am being employed to work on GraphRecipes for the next month, which is very exciting!

Over the next month, I do plan to make quite a few changes to GraphRecipes. If I had push rights, then that could save both of us a lot of time. Ultimately, the decision is up to you and the rest of the JuliaPlots community.

**Comment by mkborregaard** [comment]
Great - you now have push rights. Feel free to be creative and come up with new ideas and solutions here, we're not bound by legacy. But also appreciate still developing by branch-and-pr rather than direct commits, and to have discussions about interface and larger rearrangements.

**Pull request merged**
