### PR TITLE
Loosen RecipesBase compat; fix #93

### LINKED ISSUE #93: GraphRecipes or PlotRecipes broken?
I'm working on a package that relies heavily on GraphRecipes.

Unfortunately... when I try to use the examples I get the following:

```
MethodError: no method matching get!(::Plots.Attr, ::Symbol, ::Int64)
Closest candidates are:
  get!(!Matched::LibGit2.CachedCredentials, ::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LibGit2/src/types.jl:1276
  get!(!Matched::IdDict{K,V}, ::Any, ::Any) where {K, V} at abstractdict.jl:648
  get!(!Matched::Dict{K,V}, ::Any, ::Any) where {K, V} at dict.jl:420
  ...
```

Before updating my package yesterday this was not happening. Did I break my package manager or something?

### PR DESCRIPTION
**Pull request by asinghvi17**
#93

@caseykneale, if you check this branch out and run `]resolve`, do you get the same error as before?

### CODE REVIEW

**Comment by asinghvi17** [comment]
This seems to work locally on @caseykneale's machine, but not on CI (Plots 0.29, RecipesBase 0.8).  @mkborregaard, any thoughts on this?

**Comment by caseykneale** [comment]
Yes it does work on my machine!

**Comment by mkborregaard** [comment]
This PR should be completely safe to merge. But the Travis error shouldn't happen. If I check out master of Plots and RecipesBase I get a different error, though - markers disappear in the first example.

**Comment by asinghvi17** [comment]
Looks like we need a new Plots release @daschw

**Comment by daschw** [comment]
on it

**Comment by daschw** [comment]
https://github.com/JuliaRegistries/General/pull/9228

**Comment by JackDevine** [comment]
Thanks for this!

**Pull request merged**
