### PR TITLE
WIP: Multigraphs

### PR DESCRIPTION
**Pull request by JackDevine**
This functionality has actually always been available in GraphRecipes, however, in the past the curvature of each edge was random. I have made the curvature more deterministic and I have added the possibility for graphs with multiple self-edges.

Some examples:
```julia
using Plots
using GraphRecipes
pyplot()

graphplot([[1,1,1,2,2,2],[1,1,1],[1]], names=["hello"], nodeshape=:circle, axis_buffer=0.5, self_edge_size=0.1)
```
example1
```julia
graphplot([[1,1,1,1,1,1,2,2,2],[1,1,1],[1]], names=["hello"], nodeshape=:circle, axis_buffer=0.8)
```
example2
The second example shows that with too many self-edges, the layout gets a little silly. Perhaps I should use circles for self-edges as suggested by @mkborregaard .

### CODE REVIEW

**Comment by mkborregaard** [comment]
When do you ever need multiple self-edges? I'm not sure I've seen this in the wild. Sorry for the naive question.

**Comment by JackDevine** [comment]
That is not naive at all, I don't think that multiple self-loops/edges are a super common. Graphs with multiple self loops are usually called pseudographs:
http://mathworld.wolfram.com/Pseudograph.html

I managed to find an application of them in this paper on desalination:
https://www.sciencedirect.com/science/article/pii/S0011916417306537

Also note that multiple self loops are supported by DOT files and can be visualized by graphviz, so if we ever aspire to be able to visualize a general DOT file, then we will need to be able to support multiple self loops:
```python
import pygraphviz as pgv
import networkx as nx
from IPython.display import Image

G = nx.MultiDiGraph()
nx.add_path(G, [0, 1, 2, 3, 4])
for i in range(0, 4):
    G.add_edge(0, 3)
    G.add_edge(2, 2)

Ga = nx.nx_agraph.to_agraph(G)
Image(data=Ga.draw(format="png", prog="dot"))
``` 
multi
cc: @keorn

**Comment by mkborregaard** [comment]
Hi @JackDevine I tried to reach you on Slack, but it seems you don't come there much?

**Comment by JackDevine** [comment]
Yes, I don't use slack very often. I can't even remember my login details to be honest, I will have a look into it in a moment.

**Pull request merged**
