### PR TITLE
WIP Directed edges

### PR DESCRIPTION
**Pull request by JackDevine**
This is WIP on #55 .

The main problem that I am having is that I don't know now to resize nodes so that the labels always fit in them. I have a felling that the extent of an annotation is a function of the text, fontsize, the aspect ratio and the plot size. Although, I have no idea how to calculate this function.

My other problems are getting things to work in 3d and adding elliptical/rectangular nodeshapes. I want to work out the scaling issue before tackling those, because I feel that sorting out scaling may affect how I deal with nodeshapes and 3d.

Some examples:
```julia
using GraphRecipes
using Plots
using LightGraphs

g = DiGraph(5)
add_edge!(g, 1, 2)
add_edge!(g, 2, 1)
add_edge!(g, 3, 1)
add_edge!(g, 2, 4)
add_edge!(g, 4, 2)
add_edge!(g, 5, 3)
add_edge!(g, 5, 1)
edgelabel = ["$(i)_$(j)" for i in 1:5, j in 1:5]

graphplot(g, names=collect(1:5), nodesize=0.1, curvature_scalar=0.2,
          nodeshape=:circle, aspect_ratio=1, edgelabel=edgelabel, arrow=arrow(0.7,0.7), size=(800,800))
```
example1
```julia
n = 5
g = WheelDiGraph(n)
graphplot(g, names=repeat(["label name\nline two"],n), curvature_scalar=0.1,
          arrow=arrow(0.8,0.8), fontsize=12, size=(800,800), nodesize=0.18, nodeshape=:hexagon)
```
example2
Simply switching to pyplot improves the arrows significantly, I feel that the GR backend needs some improved arrow handling.
```julia
pyplot()
graphplot(g, names=repeat(["label name\nline two"],n), curvature_scalar=0.1,
          arrow=arrow(0.8,0.8), fontsize=12, size=(800,800), nodesize=0.18, nodeshape=:hexagon)
```
example3

And now an example where things don't work too well:
```julia
n = 5
g = WheelDiGraph(n)
graphplot(g, names=repeat(["label name\nline two"],n), curvature_scalar=0.1,
          arrow=arrow(0.8,0.8), fontsize=12, size=(400,400), nodesize=0.18, nodeshape=:hexagon)
```
example4

### CODE REVIEW

**Comment by JackDevine** [comment]
It seems that I have broken the README tests. Once I sort out the 3d issue, I will come back to that.

**Comment by mkborregaard** [comment]
First, this looks amazing. I can't tell you straight up how to deal with the default resizing - though fwiw I think a lot could be gained by using relatively big marker sizes for the default.

**Comment by JackDevine** [comment]
> First, this looks amazing.

Thanks!

> I can't tell you straight up how to deal with the default resizing

Yes, I am now beginning to believe that it is not possible find the extent of an annotation precisely. I might just experiment around with some different text/fontsize/aspect_ratio/plot_size and see if I can find some sort of approximate dimensions to resize to.

> a lot could be gained by using relatively big marker sizes for the default.

I am glad that you think so, that way I can take my approximate resizing and just add to it a little bit and nobody will notice.

**Comment by JackDevine** [comment]
I have changed the code so that we use he shape seriestype to create nodes as discussed in #55 .

I had to approximate the extent of a piece of text using the function `annotation_extent` (see utils.jl:145). This function relies heavily on magic numbers, so it would be nice to replace it with a function that is more systematic. Also, since we are not dealing with monospace fonts, the function tends to overestimate the extent of a piece of text by quite a bit.

I have not managed to get this working in 3d. I think that I will try and sort out all of the 3d issues in a separate PR.

Important! This commit is breaking. I have moved away from using `markersize` and `marker_z` to control the properties of nodes. The user now controls node properties through the following kwargs:

```
                   nodeshape = :hexagon,
                   nodesize = 0.1,
                   nodecolor = 1,
```
`nodecolor` can be either a single color or an array. One consequence of this change is that I had to change the first example in the README.

An example:
```julia
n = 8
g = WheelDiGraph(n)
graphplot(g, names=repeat(["label name"],n), curvature_scalar=0.0,
          fontsize=12, size=(800,800), nodeshape=:ellipse, axis_buffer=0.4)
```
wheel

**Pull request merged**
