### PR TITLE
Tentative fix for PGFPlotsX.jl downstream issue

### PR DESCRIPTION
**Pull request by Holbormon**
Closes https://github.com/JuliaPlots/GraphRecipes.jl/issues/198.

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
I would prefer to wrap it in `@debug` than to remove it completely

**Comment by Holbormon** [comment]
> I would prefer to wrap it in `@debug` than to remove it completely

I'm not too familiar with this macro. Will it prevent the variable from ending up in the generated @series ?

**Comment by BeastyBlacksmith** [comment]
Hmm... I thought the difference between the type trees in 1.6 and 1.10 came from the circles in the nodes, but doesn't seem to be the case.
But this accidentally fixes #188 I guess

**Comment by BeastyBlacksmith** [comment]
For reference:
# 1.10

julia_type_tree1 10

# 1.6

**Comment by BeastyBlacksmith** [comment]
🤦🏻 , so julia 1.10. added a new type...

**Pull request merged**
