### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by harryscholes**

### CODE REVIEW

**Comment by ericphanson** [comment]
The example works on master already (without this PR); I think the problem is just that the last release was a long time ago.

**Comment by mkborregaard** [comment]
@JackDevine do we need a release do you think?

**Comment by JackDevine** [comment]
Hi @harryscholes 

I really appreciate your work on this fix, although I will use the fix in #88 instead.

Sorry about all of the confusion around this, I really shouldn't have had things on the readme not working on the latest release. The fix in this PR ultimately got incorporated in #88 , however, I also made sure that `markershape` worked on master as well in #88.

I definitely had a plan to fix this issue, but I just didn't communicate it very clearly (or at all). I hope that you wont be discouraged from making fixes in the future.

**Comment by harryscholes** [comment]
No problem at all! Keep up the good work with this package

**Comment by tbenst** [comment]
New user to package, seems really well thought out. Spent quite a while trying to figure out why example was broken, would be nice for this to be merged or new release tagged.

**Comment by mkborregaard** [comment]
Could be some of the packages in JuliaPro keeping back the deps of this one from full updating.

**Comment by JackDevine** [comment]
What happens if you type `]st` at the REPL?

**Comment by tbenst** [comment]
Thanks for the comments, a simple `] update` fixed it!

**Pull request closed without merging**
